[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pcntl', 'php82Extensions.pdo', 'php82Extensions.mbstring', 'php82Extensions.tokenizer', 'php82Extensions.xml', 'php82Extensions.ctype', 'php82Extensions.json', 'php82Extensions.bcmath', 'php82Extensions.fileinfo', 'php82Extensions.pdo_mysql']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = ['npm ci', 'npm run build']

[start]
cmd = 'bash -c "(php artisan reverb:start --host=0.0.0.0 --port=8080 &) && php artisan serve --host=0.0.0.0 --port=$PORT"'
